In [ ]:
from datetime import datetime, timedelta
from google_play_scraper import app as get_app, reviews_all, Sort
import numpy as np
import pandas as pd

### Scrapping

In [ ]:
# crawling
result_im3 = reviews_all(
    "com.pure.indosat.care",
    lang="id",
    country="id",
    sort=Sort.NEWEST,
    sleep_milliseconds=2000,  # Jeda aman agar tidak terblokir
)

# bentuk df
df_im3 = pd.DataFrame(np.array(result_im3), columns=["review"])
df_im3 = df_im3.join(pd.DataFrame(df_im3.pop("review").values.tolist()))

# filter 1 tahun terakhir
satu_tahun= datetime.now() - timedelta(days=365)
df_im3["at"] = pd.to_datetime(df_im3["at"])
df_im3_filtered = df_im3[df_im3["at"] >= satu_tahun_lalu].copy()
df_im3_filtered = df_im3_filtered[["userName", "score", "content", "at"]]
df_im3_filtered.columns = ["username", "rating pengguna", "review", "tanggal"]
df_im3_final = df_im3_filtered.sort_values(by="tanggal", ascending=False)
df_im3_final

,username,rating pengguna,review,tanggal
0,Pengguna Google,1,saya beli paket data.sudah di teranfer tapi ku...,2026-06-22 13:36:05
1,Pengguna Google,5,main game,2026-06-22 13:30:16
2,Pengguna Google,5,lancar jaya,2026-06-22 13:27:17
3,Pengguna Google,1,sinyal jelek,2026-06-22 13:25:15
4,Pengguna Google,1,jaringannya super JELEK JAKARTA BARAT SERENGSENG,2026-06-22 13:24:20
...,...,...,...,...
91729,Pengguna Google,1,mahal tapi lemot,2025-06-23 13:24:16
91730,Pengguna Google,5,apk ini sekarang kadang aga eror,2025-06-23 13:22:09
91731,Pengguna Google,1,"review belum sebulan pake im3, awalnya bagus b...",2025-06-23 13:20:52
91732,Pengguna Google,5,very good,2025-06-23 13:15:49
91733,Pengguna Google,4,mantap,2025-06-23 13:15:09

In [ ]:
# cek tanggal terbaru hingga terlama
print(df_im3_final["tanggal"].max())
print(df_im3_final['tanggal'].min())

2026-06-22 13:36:05
2025-06-23 13:15:09

In [ ]:
# count total data
print(df_im3_final.shape[0])

91734

In [ ]:
# cek missing value
df_im3_final.isnull().sum()

username           0
rating pengguna    0
review             0
tanggal            0
dtype: int64

In [ ]:
# save ke bentuk csv
df_im3_final.to_csv("data_review_im3.csv", index=False, encoding='utf-8')